// ============================================================================
// >>>>>>>>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// ----------------------------------------------------------------------------
// Copyright (c) 2006-2011 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED 
// ----------------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS AUTO-GENERATED BY THE LATTICEMICO SYSTEM.
//
// Permission:
//
//      Lattice Semiconductor grants permission to use this code
//      pursuant to the terms of the Lattice Semiconductor Corporation
//      Open Source License Agreement.  
//
// Disclaimer:
//
//      Lattice Semiconductor provides no warranty regarding the use or
//      functionality of this code. It is the user's responsibility to
//      verify the user’s design for consistency and functionality through
//      the use of formal verification methods.
//
// ----------------------------------------------------------------------------
//
//                  Lattice Semiconductor Corporation
//                  5555 NE Moore Court
//                  Hillsboro, OR 97214
//                  U.S.A
//
//                  TEL: 1-800-Lattice (USA and Canada)
//                         503-286-8001 (other locations)
//
//                  web: http://www.latticesemi.com/
//                  email: techsupport@latticesemi.com
//
// ----------------------------------------------------------------------------
//                         FILE DETAILS
//
// Name			: lm8_include_all.v
// Project		: LatticeMico8
// Dependencies	: system_conf.v
// Description	: LatticeMico8 microcontroller core's include file.
// Revisions	: 3.2 (Initial version)
// 				: 3.3
//					- Dependency to system_conf.v (for `timescale)
// ============================================================================
`ifndef SIMULATION
`include "pmi_def.v"
`endif
`include "system_conf.v"
`include "../components/lm8/rtl/verilog/lm8_include.v"
`include "../components/lm8/rtl/verilog/lm8_interrupt.v"
`include "../components/lm8/rtl/verilog/lm8_io_cntl.v"
`include "../components/lm8/rtl/verilog/lm8_flow_cntl.v"
`include "../components/lm8/rtl/verilog/lm8_idec.v"
`include "../components/lm8/rtl/verilog/lm8_alu.v"
`include "../components/lm8/rtl/verilog/lm8_core.v"
`include "../components/lm8/rtl/verilog/lm8_top.v"
