-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.2.115
-- Module  Version: 5.7
-- Wed Mar 13 23:14:19 2019

-- parameterized module component declaration
component pll0
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : pll0
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, LOCK=>__);
