`define LATTICE_FAMILY "MachXO2"
`define LATTICE_FAMILY_MachXO2
`define LATTICE_DEVICE "LCMXO2-7000HE"
`ifndef SYSTEM_CONF
`define SYSTEM_CONF
`timescale 1ns / 100 ps
`define I_WB_DAT_WIDTH 8
`define D_WB_DAT_WIDTH 8
`define CFG_REGISTER_COUNT 16
`define LM8CFG_REGISTER_16
`define LM8CFG_DISTRIBUTED_RAM
`define CFG_CALL_STACK 16
`define LM8CFG_CALL_STACK_8
`define LM8CFG_PROM_SIZE 1024
`define LM8CFG_PROM_INIT_FILE "lm8_cic/fw/prom_init.mem"
`define LM8CFG_PROM_INIT_FILE_FORMAT "hex"
`define SP_ADDRESS_LOCK
`define SP_PORT_TYPE "Memory"
`define LM8SP_PORT_ENABLE
`define LM8CFG_SP_INIT_FILE "lm8_cic/fw/scratchpad_init.mem"
`define LM8CFG_SP_INIT_FILE_FORMAT "hex"
`define CFG_EXT_SIZE 16
`define LM8CFG_EXT_SIZE_8
`define CFG_IO_BASE_ADDRESS 32'h80000000
`define LM8LATTICE_FAMILY "MachXO2"
`define ioGPIO_WB_DAT_WIDTH 8
`define ioGPIO_WB_ADR_WIDTH 4
`define ADDRESS_LOCK
`define ioBOTH_INPUT_AND_OUTPUT
`define ioDATA_WIDTH 32'h1
`define ioINPUT_WIDTH 32'h3
`define ioOUTPUT_WIDTH 32'h1
`endif // SYSTEM_CONF
